'\" t
.\"     Title: cowsay
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 05/28/2020
.\"    Manual: Cowsay Manual
.\"    Source: Cowsay 3.6.0-SNAPSHOT
.\"  Language: English
.\"
.TH "COWSAY" "1" "05/28/2020" "Cowsay 3\&.6\&.0\-SNAPSHOT" "Cowsay Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
cowsay, cowthink \- configurable speaking/thinking cow (and a bit more)
.SH "SYNOPSIS"
.sp
\fBcowsay\fR [\fB\-e\fR \fIeye_string\fR] [\fB\-f\fR \fIcowfile\fR] [\fB\-h\fR] [\fB\-l\fR] [\fB\-n\fR] [\fB\-T\fR \fItongue_string\fR] [\fB\-W\fR \fIcolumn\fR] [\fB\-bdgpstwy\fR]
.SH "DESCRIPTION"
.sp
\fICowsay\fR generates an ASCII picture of a cow saying something provided by the user\&. If run with no arguments, it accepts standard input, word\-wraps the message given at about 40 columns, and prints the cow saying the given message on standard output\&.
.sp
To aid in the use of arbitrary messages with arbitrary whitespace, use the \fB\-n\fR option\&. If it is specified, the given message will not be word\-wrapped\&. This is possibly useful if you want to make the cow think or speak in figlet(6)\&. If \fB\-n\fR is specified, there must not be any command line arguments left after all the switches have been processed\&.
.sp
The \fB\-W\fR specifies roughly where the message should be wrapped\&. The default is equivalent to \fB\-W 40\fR (i\&.e\&. wrap words at or before the 40th column)\&.
.sp
If any command\-line arguments are left over after all switches have been processed, they become the cow\(cqs message\&. The program will not accept standard input for a message in this case\&.
.sp
If the program is invoked as \fBcowthink\fR then the cow will think its message instead of saying it\&.
.SH "OPTIONS"
.sp
There are several provided modes which change the appearance of the cow depending on its particular emotional/physical state\&.
.PP
\fB\-b\fR
.RS 4
Invokes Borg mode\&.
.RE
.PP
\fB\-d\fR
.RS 4
Causes the cow to appear dead\&.
.RE
.PP
\fB\-g\fR
.RS 4
Invokes greedy mode\&.
.RE
.PP
\fB\-p\fR
.RS 4
Causes a state of paranoia to come over the cow\&.
.RE
.PP
\fB\-s\fR
.RS 4
Makes the cow appear thoroughly stoned\&.
.RE
.PP
\fB\-t\fR
.RS 4
Yields a tired cow\&.
.RE
.PP
\fB\-w\fR
.RS 4
Is somewhat the opposite of
\fB\-t\fR, and initiates wired mode\&.
.RE
.PP
\fB\-y\fR
.RS 4
Brings on the cow\(cqs youthful appearance\&.
.RE
.PP
\fB\-e\fR
.RS 4
Selects the appearance of the cow\(cqs eyes, in which case the first two characters of the argument string
\fIeye_string\fR
will be used\&. The default eyes are
\fBoo\fR\&. The tongue is similarly configurable through
\fB\-T\fR
and
\fItongue_string\fR; it must be two characters and does not appear by default\&. However, it does appear in the
\fIdead\fR
and
\fIstoned\fR
modes\&. Any configuration done by
\fB\-e\fR
and
\fB\-T\fR
will be lost if one of the provided modes is used\&.
.RE
.PP
\fB\-f\fR
.RS 4
Specifies a particular cow picture file (\fIcowfile\fR) to use\&. If the cowfile spec contains
\fI/\fR
then it will be interpreted as a path relative to the current directory\&. Otherwise, cowsay will search the COWPATH\&. Additional cowpath entries may be specified in the
\fBCOWPATH\fR
environment variable\&. To list all cowfiles on the current*COWPATH*, invoke
\fBcowsay\fR
with the
\fB\-l\fR
switch\&.
.RE
.SH "COWFILE FORMAT"
.sp
A cowfile is made up of a simple block of \fBperl(1)\fR code, which assigns a picture of a cow to the variable \fB$the_cow\fR\&. Should you wish to customize the eyes or the tongue of the cow, then the variables \fB$eyes\fR and \fB$tongue\fR may be used\&. The trail leading up to the cow\(cqs message balloon is composed of the character(s) in the \fB$thoughts\fR variable\&. Any backslashes must be reduplicated to prevent interpretation\&. Also, at\-signs ("@") must be backslashed because that is what Perl 5 expects\&. The name of a cowfile must end with \fB\&.cow\fR, otherwise it is not recognized as a cowfile\&.
.SH "ENVIRONMENT"
.sp
The \fBCOWPATH\fR environment variable, if present, will be used to search for cowfiles\&. It contains a colon\-separated list of directories, much like \fBPATH\fR or \fBMANPATH\fR\&.
.sp
The default \fBCOWPATH\fR is searched after entries in the user\-specified \fBCOWPATH\fR environment variable\&. To suppress this behavior (e\&.g\&. for development work), set the \fBCOWSAY_ONLY_COWPATH\fR environment variable to \fB1\fR\&. In this case, \fBCOWPATH\fR should contain at least a directory with a file called \fBdefault\&.cow\fR in it\&.
.SH "FILES"
.sp
\fB%PREFIX%/share/cows\fR holds a sample set of cowfiles\&. If your \fBCOWPATH\fR is not explicitly set, it automatically contains this directory\&.
.sp
\fB%PREFIX%/share/site\-cows\fR is provided for administrators to install custom cows\&. Cows in \fBshare/site\-cows\fR take precedence over cows with the same name in \fBshare/cows\fR\&. The \fBsite\-cows\fR directory will never be modified by cowsay installations, so custom cows defined there will persist across upgrades of cowsay\&.
.SH "BUGS"
.sp
If there are any, please report them on the cowsay GitHub page (https://github\&.com/cowsay\-org/cowsay/issues) or notify the author at the address below\&.
.SH "AUTHOR"
.sp
Cowsay is maintained by Andrew Janke (floss@apjanke\&.net)\&.
.sp
Cowsay was originally written by Tony Monroe (tony@nog\&.net), with suggestions from Shannon Appel (appel@csua\&.berkeley\&.edu) and contributions from Anthony Polito (aspolito@csua\&.berkeley\&.edu)\&.
.SH "RESOURCES"
.sp
GitHub: https://github\&.com/cowsay\-org/cowsay
.sp
Main web site: http://cowsay\&.diamonds
.SH "SEE ALSO"
.sp
\fBperl(1)\fR, \fBwall(1)\fR, \fBnwrite(1)\fR, \fBfiglet(6)\fR
